### PR TITLE
Generate TOML file for contributors instead of a MD file

### PR DESCRIPTION
**Pull request by doup**
By generating a TOML file instead of MD it gives use the flexibility to generate better HTML code via templates.

Use this shortcode in the announcement post:

```jinja
<!-- Contributors -->
{{ contributors(path = "./release-content/0.14/contributors.toml")}}
```

Which will show the contributors like this:

image

---

For me:
- it's better than a single column list
- it's easy to improve in the future
- the improvements will automatically get backported to older announcement posts

### CODE REVIEW

**Comment by doup** [comment]
I noticed the section didn't reflect on the TOC because I was using an `.html` shortcode, I've changed it to `.md` so now it works.

**Comment by doup** [comment]
I've changed the names to show centered, the reason being that it just looks better imo (specially on smaller screens)… but can be easily reverted:

image

image

**Comment by IceSentry** [comment]
I like the idea of using a shortcode for this, but I'd prefer if this PR didn't contain any style change. I'd prefer if any style decision was made in PRs after all the base generation stuff is merged.

**Comment by IceSentry** [comment]
Also, the contributors, in 99% of cases are github usernames so it was pretty intentional to use the `@name` format. There's a few issues with the generation and about 1% of the list ends up being a git name instead of a github user name but I think it's fine to use the `@` syntax.

**Comment by IceSentry** [comment]
Actually, that reminds me, I think I can detect those cases and don't add the `@` for those that aren't usernames. So I guess it's fine if your PR doesn't add the `@` automatically

**Comment by doup** [comment]
@IceSentry I've created [a new PR](https://github.com/IceSentry/bevy-website/pull/10) as I noticed that a couple of your commits slipped in this PR… to now realize that it didn't matter as these commits didn't introduce any extra changes. 🙈🙃 

Anyway, I'll close this PR in favor of the new one, which does the minimum to move contributors to a TOML file. Styling, layout and `@` not touched.

**Pull request closed without merging**
