### PR TITLE
Order roughly by impact

### PR DESCRIPTION
**Pull request by rparrett**
Diff looks super weird so it's a bit hard to be 1000% confident that I didn't mangle this, but I did glance at the rendered output and verify that the same number of lines/headers are present.

There are many sections that seemed very unlikely to break **user** code or that I didn't really understand so it was a bit difficult.

Many sections are not actually breaking and should be deleted and I'll follow up with individual suggestions later.

Scene/reflect stuff maybe should be higher, but those sections are huge and they are at least grouped togetherish now.

### CODE REVIEW

**Comment by IceSentry** [comment]
oof, yeah, the diff is something else, I'll pull it locally and do quick run over before merging.

**Comment by IceSentry** [comment]
Is there any kind of heuristic for the ordering or is it purely by feeling? Just want to know if the generator could output something in a better order in the future. Maybe weight it based on the amount of reacts?

**Comment by rparrett** [comment]
My only thought is "number of examples impacted" but that it would be a bit of a lift.

This effort was purely by feeling after migrating a couple personal projects and a couple ecosystem crates.

**Comment by IceSentry** [comment]
This seems good to me

Notes for after the merge
Move impl bundle for components closer to spawn take bundle
Move the time scaling closer to bool argument on timer just because it's time related
Move the removal of watch_for_changes closer to new plugin settings just to keep similar changes close together
Remove `bevy_pbr:/bevy_scene` and other similar prefix for consistency

In the future, I think I'll generate the migration guide based on Area tag. It would probably be easier to follow.

**Comment by rparrett** [comment]
Those tweaks all make sense to me.

**Comment by IceSentry** [comment]
I'll commit them in a few minutes

**Pull request merged**
